version: "3.2"

services:
  dev:
    container_name: ventur-node
    image: paritytech/ci-linux:production
    working_dir: /var/www/ventur-node
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/ventur-node/.cargo
    volumes:
      - .:/var/www/ventur-node
    command: bash -c "cargo build --release"