[workspace]
members = [
    "node",
    "pallets/escrow",
    "pallets/payments",
    "pallets/rfp",
    "pallets/nt-nft",
    "pallets/subscription",
    "runtime",
]
[profile.release]
panic = "unwind"
