name: "Install Rust"
runs: 
  using: "composite"
  steps: 
    - run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source ~/.cargo/env
        rustup default stable
        rustup update stable 
        rustup update nightly 
        rustup install nightly-2022-09-19 
        rustup override set nightly-2022-09-19
        rustup target add wasm32-unknown-unknown
        rustup target add wasm32-unknown-unknown --toolchain nightly 
      shell: bash 