name: Cargo Build Release and Lint Validation

# Controls when the action will run.
on:
  # Triggers the workflow on pushes
  push:
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'docs/**'
      - '.gitignore'
      - '**.md'
      - '**.png'
      - '**/tests.rs'
      - '**/mock.rs'
    branches: 
      - main 
  pull_request:
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'docs/**'
      - '.gitignore'
      - '**.md'
      - '**.png'
      - '**/tests.rs'
      - '**/mock.rs'
    branches:
      - main 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-release-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set-up substrate requirements
        run: |
          sudo apt install -y build-essential
          sudo apt install -y git clang curl libssl-dev llvm libudev-dev make protobuf-compiler

      - name: Install and configure Rust
        uses: ./.github/actions/install-rust 

      - name: Cargo Clippy 
        run: |
          cargo clippy
          cargo clean

      - name: Cargo Build
        run: |
          cargo build --release

  check-release-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set-up substrate requirements
        run: |
          brew update 
          brew install openssl

      - name: Install and configure Rust
        uses: ./.github/actions/install-rust 

      - name: Cargo Clippy 
        run: |
          cargo clippy
          cargo clean

      - name: Cargo Build
        run: |
          cargo build --release