name: Cargo Check Release

# Controls when the action will run.
on:
  # Triggers the workflow on pushes
  push:
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'docs/**'
      - '.gitignore'
      - '**/README.md'
      - '**/tests.re'
      - '**/mock.rs'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set-up
        run: sudo apt install -y git clang curl libssl-dev llvm libudev-dev make protobuf-compiler

      - name: Install and configure Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source ~/.cargo/env
          rustup default stable
          rustup update stable 
          rustup install nightly-2022-09-19 
          rustup override set nightly-2022-09-19
          rustup target add wasm32-unknown-unknown
          rustup target add wasm32-unknown-unknown --toolchain nightly 

      - name: Cargo Check
        run: |
          SKIP_WASM_BUILD=1 cargo check --release

      - name: Cargo Clippy 
        run: |
          cargo clippy