name: Check Docker Compose

# Controls when the action will run.
on:
  # Triggers the workflow on pushes
  push:
    paths-ignore:
      - '.vscode/**'
      - 'docs/**'
      - '.gitignore'
      - '**.md'
      - '**.png'
      - '**/tests.rs'
      - '**/mock.rs'
    branches-ignore:
      - main 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-commit-ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup docker and docker-compose
        run: | 
           sudo apt-get remove docker docker-engine docker.io containerd runc
           sudo apt-get update
           sudo apt-get install ca-certificates curl gnupg lsb-release
           sudo mkdir -p /etc/apt/keyrings
           curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
           echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
           sudo apt-get update
           sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
          
      - name: docker compose 
        run: | 
          cd .github/scripts/
          docker-compose down --remove-orphans 
          docker-compose run --rm --service-ports dev $@