name: Create and publish Docker image to Docker Hub

on:
  push:
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'docs/**'
      - '.gitignore'
      - '**.md'
      - '**.png'
      - '**/tests.rs'
      - '**/mock.rs'
    branches: 
      - main 
  pull_request:
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'docs/**'
      - '.gitignore'
      - '**.md'
      - '**.png'
      - '**/tests.rs'
      - '**/mock.rs'
    branches:
      - main 

  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: popularcoding/ventur
          tags: |
                type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}