name: Escrow Unit Tests

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for the master branch
  push:
    paths: 
      - 'pallets/escrow/**'
    branches-ignore:
      - main 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-escrow-pallet:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set-Up
        run: |
          sudo apt install -y build-essential
          sudo apt install -y git clang curl libssl-dev llvm libudev-dev make protobuf-compiler

      - name: Install and configure Rust
        uses: ./.github/actions/install-rust 

      - name: Check Escrow Pallets Unit Tests
        run: |
          SKIP_WASM_BUILD=1 cargo test -p pallet-escrow
